# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 16 Jul 2020 21:03:00 +0000
*               @ALL          0
*               @user         8
