# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 16 Jul 2020 21:03:00 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$1$Cy3UXt6T$4pIhR3JKJgyAgwZfEHG8g/:Ravi Bhagyoday:rbhagyoday.rb@gmail.com:admin,user
